name: Generate Py-Shiny Examples

on:
  workflow_dispatch:
    inputs:
      syntaxType:
        description: 'Enter the syntax for the apps (core or express)'
        required: true
      modelType:
        description: 'Enter the model you want to use (haiku3, haiku3.5 or sonnet)'
        required: true

jobs:
  create-py-shiny-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate syntax type
        if: github.event.inputs.syntaxType != 'core' && github.event.inputs.syntaxType != 'express'
        run: |
            echo "Invalid syntax type. Please enter one of the following options only: core, or express"
            exit 1

      - name: Validate model type
        if: github.event.inputs.modelType != 'haiku3' && github.event.inputs.modelType != 'haiku3.5' && github.event.inputs.modelType != 'sonnet'
        run: |
            echo "Invalid model type. Please enter one of following options only: haiku3, haiku3.5, or sonnet"
            exit 1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python create_apps_using_llm.py ${{ github.event.inputs.syntaxType }} ${{ github.event.inputs.modelType }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: 'Generated Py-shiny examples using: ${{ github.event.inputs.syntaxType }} syntax leveraging ${{ github.event.inputs.modelType }} models'
          body: 'All empty py-examples directories with a `PROMPT.md` have been filled with app.py by leveraging AI models.'
          labels: 'automated'
          branch: 'processed-output-${{ github.run_id }}'
          commit-message: 'Automatically add py-shiny examples: ${{ github.event.inputs.syntaxType }} and ${{ github.event.inputs.modelType }}'